b) 

Use call option prices from the two csv-files found at the homepage of the course
to estimate two local volatility surfaces using Dupire's formula. Each row in the 
csv-files consists of data on the form

Time to maturity, Strike price, Call option price.

Set r = 0 and approximate the derivatives in the Dupire formula using finite differences.

In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('New_option_prices_1.csv')
df_2 =pd.read_csv('New_option_prices_2.csv')

In [24]:
df['TimeToMaturity'].unique()

array([0.024658, 0.10137 , 0.17808 , 0.34795 , 0.84932 ])

In [26]:
df['StrikePrice'].unique()

array([1550, 1560, 1570, 1580, 1590, 1600, 1610, 1620, 1630, 1640, 1650,
       1660, 1670, 1680, 1690, 1700, 1710, 1720, 1730, 1740, 1750])

In [30]:
df['CallOptionPrice'].unique() #All options have unique prices. 

array([4.5188e+01, 3.7096e+01, 2.9562e+01, 2.2739e+01, 1.6771e+01,
       1.1770e+01, 7.7927e+00, 4.8206e+00, 2.7572e+00, 1.4419e+00,
       6.8155e-01, 2.8773e-01, 1.0721e-01, 3.4846e-02, 9.7665e-03,
       2.3344e-03, 4.7080e-04, 7.9310e-05, 1.1053e-05, 1.2631e-06,
       1.1736e-07, 5.0624e+01, 4.2426e+01, 3.4423e+01, 2.6799e+01,
       2.1554e+01, 1.7655e+01, 1.4320e+01, 1.1486e+01, 9.1072e+00,
       7.1363e+00, 5.5257e+00, 4.2273e+00, 3.1951e+00, 2.3857e+00,
       1.7597e+00, 1.2823e+00, 9.2304e-01, 6.5640e-01, 4.6116e-01,
       3.2010e-01, 2.1954e-01, 5.6226e+01, 4.7801e+01, 4.0494e+01,
       3.4120e+01, 2.8558e+01, 2.3724e+01, 1.9550e+01, 1.5975e+01,
       1.2942e+01, 1.0393e+01, 8.2747e+00, 6.5312e+00, 5.1112e+00,
       3.9666e+00, 3.0532e+00, 2.3313e+00, 1.7663e+00, 1.3282e+00,
       9.9146e-01, 7.3488e-01, 5.4098e-01, 6.8283e+01, 6.2310e+01,
       5.6618e+01, 5.1215e+01, 4.6106e+01, 4.1296e+01, 3.6790e+01,
       3.2588e+01, 2.8691e+01, 2.5098e+01, 2.1804e+01, 1.8803e

In [25]:
df_2['TimeToMaturity'].unique()

array([0.021918, 0.09863 , 0.17534 , 0.34521 , 0.59726 ])

In [31]:
0.84932-0.34795

0.50137

In [32]:
0.34795-0.17808

0.16987

In [33]:
0.17808-0.10137

0.07670999999999999

In [34]:
0.10137-0.024658

0.076712